version: 1.0.{build}
os: Visual Studio 2013
environment:
  CMAKE_PREFIX_PATH: C:\Qt\5.5\msvc2013_64
build_script:
- cmd: >-
    call "C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat" x64

    mkdir build

    cd build

    cmake -G "NMake Makefiles" ..

    nmake
test_script:
- cmd: ctest