version: 1.0.{build}
image: Visual Studio 2017
environment:
  CMAKE_PREFIX_PATH: C:\Qt\5.11\msvc2017_64
build_script:
- cmd: >-
    call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvars64.bat"

    mkdir build

    cd build

    cmake -G "Visual Studio 15 2017 Win64" ..

    cmake --build . --config Debug
test_script:
- cmd: ctest -C Debug -T Test --no-compress-output
