version: 1.0.{build}
image: Visual Studio 2019
environment:
  CMAKE_PREFIX_PATH: C:\Qt\6.2\msvc2019_64
build_script:
- cmd: >-
    call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Auxiliary\Build\vcvarsall.bat" x64

    mkdir build

    cd build

    cmake -G "Visual Studio 16 2019" ..

    cmake --build . --config Debug
test_script:
- cmd: ctest -C Debug -T Test --no-compress-output
